//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adpemployee_staging1
    {
        public Nullable<System.DateTime> dsc_emp_hire_dt { get; set; }
        public string dsc_emp_email_addr { get; set; }
        public string dsc_emp_adp_id { get; set; }
        public string dsc_emp_perm_id { get; set; }
        public string RP_Emp { get; set; }
        public string dsc_emp_can_be_obs_yn { get; set; }
        public string dsc_emp_hourly_yn { get; set; }
        public string dsc_emp_temp_yn { get; set; }
        public string dsc_emp_added_id { get; set; }
        public System.DateTime dsc_emp_added_dtm { get; set; }
        public string dsc_emp_upd_uid { get; set; }
        public string dsc_emp_upd_dtm { get; set; }
        public string Person_ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string loc { get; set; }
        public string dsc_lc_code { get; set; }
        public int dsc_lc_id { get; set; }
        public System.DateTime TodaysDate { get; set; }
    }
}
