//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsc_delnow
    {
        public int dsc_emp_id { get; set; }
        public Nullable<int> dsc_assigned_lc_id { get; set; }
        public string dsc_emp_perm_id { get; set; }
        public Nullable<int> dsc_emp_wms_clock_nbr { get; set; }
        public string dsc_emp_first_name { get; set; }
        public string dsc_emp_mid_name { get; set; }
        public string dsc_emp_last_name { get; set; }
        public string dsc_emp_email_addr { get; set; }
        public string dsc_emp_title { get; set; }
        public string dsc_emp_adp_id { get; set; }
        public Nullable<System.DateTime> dsc_emp_hire_dt { get; set; }
        public System.DateTime dsc_emp_init_work_dt { get; set; }
        public Nullable<System.DateTime> dsc_emp_term_dt { get; set; }
        public string dsc_emp_can_be_obs_yn { get; set; }
        public string dsc_emp_temp_yn { get; set; }
        public string dsc_emp_hourly_yn { get; set; }
        public string dsc_emp_added_id { get; set; }
        public System.DateTime dsc_emp_added_dtm { get; set; }
        public string dsc_emp_upd_uid { get; set; }
        public Nullable<System.DateTime> dsc_emp_upd_dtm { get; set; }
    }
}
