//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_CUSTOMER
    {
        public DSC_CUSTOMER()
        {
            this.OBS_INST = new HashSet<OBS_INST>();
            this.OBS_COLLECT_FORM_TMPLT = new HashSet<OBS_COLLECT_FORM_TMPLT>();
        }
    
        public int dsc_cust_id { get; set; }
        public string dsc_cust_name { get; set; }
        public string dsc_cust_parent_name { get; set; }
        public Nullable<System.DateTime> dsc_cust_eff_end_date { get; set; }
    
        public virtual ICollection<OBS_INST> OBS_INST { get; set; }
        public virtual ICollection<OBS_COLLECT_FORM_TMPLT> OBS_COLLECT_FORM_TMPLT { get; set; }
    }
}
