//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSC_EMPLOYEE
    {
        public DSC_EMPLOYEE()
        {
            this.OBS_API_EVENT_LOG = new HashSet<OBS_API_EVENT_LOG>();
            this.OBS_COLLECT_FORM_INST = new HashSet<OBS_COLLECT_FORM_INST>();
            this.OBS_COL_FORM_INST_SIGS = new HashSet<OBS_COL_FORM_INST_SIGS>();
            this.OBS_RVW_FORM_INST = new HashSet<OBS_RVW_FORM_INST>();
            this.OBS_INST = new HashSet<OBS_INST>();
        }
    
        public int dsc_emp_id { get; set; }
        public Nullable<int> dsc_assigned_lc_id { get; set; }
        public string dsc_emp_perm_id { get; set; }
        public string dsc_emp_supvsr_perm_id { get; set; }
        public Nullable<int> dsc_emp_wms_clock_nbr { get; set; }
        public string dsc_emp_first_name { get; set; }
        public string dsc_emp_mid_name { get; set; }
        public string dsc_emp_last_name { get; set; }
        public string dsc_emp_email_addr { get; set; }
        public string dsc_emp_title { get; set; }
        public string dsc_emp_adp_id { get; set; }
        public Nullable<System.DateTime> dsc_emp_hire_dt { get; set; }
        public System.DateTime dsc_emp_init_work_dt { get; set; }
        public Nullable<System.DateTime> dsc_emp_term_dt { get; set; }
        public string dsc_emp_can_be_obs_yn { get; set; }
        public string dsc_emp_temp_yn { get; set; }
        public string dsc_emp_hourly_yn { get; set; }
        public string dsc_emp_pri_src { get; set; }
        public string dsc_emp_added_id { get; set; }
        public System.DateTime dsc_emp_added_dtm { get; set; }
        public string dsc_emp_upd_uid { get; set; }
        public Nullable<System.DateTime> dsc_emp_upd_dtm { get; set; }
    
        public virtual ICollection<OBS_API_EVENT_LOG> OBS_API_EVENT_LOG { get; set; }
        public virtual ICollection<OBS_COLLECT_FORM_INST> OBS_COLLECT_FORM_INST { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_SIGS> OBS_COL_FORM_INST_SIGS { get; set; }
        public virtual ICollection<OBS_RVW_FORM_INST> OBS_RVW_FORM_INST { get; set; }
        public virtual ICollection<OBS_INST> OBS_INST { get; set; }
        public virtual DSC_LC DSC_LC { get; set; }
    }
}
