//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_QUEST_SLCT_ANS
    {
        public long obs_qsa_id { get; set; }
        public Nullable<int> obs_qat_id { get; set; }
        public string obs_qsa_text { get; set; }
        public short obs_qsa_order { get; set; }
        public Nullable<short> obs_qsa_wt { get; set; }
        public string obs_qsa_dflt_yn { get; set; }
        public System.DateTime obs_qsa_eff_st_dt { get; set; }
        public System.DateTime obs_qsa_eff_end_dt { get; set; }
    
        public virtual OBS_QUEST_ANS_TYPES OBS_QUEST_ANS_TYPES { get; set; }
    }
}
