//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_USER_ROLE
    {
        public int obs_user_role_id { get; set; }
        public int obs_user_auth_id { get; set; }
        public int obs_role_id { get; set; }
        public System.DateTime obs_user_role_eff_start_dt { get; set; }
        public System.DateTime obs_user_role_eff_end_dt { get; set; }
    
        public virtual OBS_ROLE OBS_ROLE { get; set; }
        public virtual OBS_USER_AUTH OBS_USER_AUTH { get; set; }
    }
}
