//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_COL_FORM_QUESTIONS
    {
        public OBS_COL_FORM_QUESTIONS()
        {
            this.OBS_COL_FORM_INST_QUEST = new HashSet<OBS_COL_FORM_INST_QUEST>();
        }
    
        public long obs_col_form_quest_id { get; set; }
        public int obs_cft_id { get; set; }
        public int obs_form_section_id { get; set; }
        public Nullable<int> obs_form_sub_section_id { get; set; }
        public int obs_qat_id { get; set; }
        public short obs_col_form_quest_order { get; set; }
        public Nullable<short> obs_col_form_quest_wgt { get; set; }
        public string obs_col_form_quest_na_yn { get; set; }
    
        public virtual ICollection<OBS_COL_FORM_INST_QUEST> OBS_COL_FORM_INST_QUEST { get; set; }
        public virtual OBS_COLLECT_FORM_TMPLT OBS_COLLECT_FORM_TMPLT { get; set; }
        public virtual OBS_FORM_SECTION OBS_FORM_SECTION { get; set; }
        public virtual OBS_FORM_SECTION OBS_FORM_SECTION1 { get; set; }
        public virtual OBS_QUEST_ANS_TYPES OBS_QUEST_ANS_TYPES { get; set; }
    }
}
