//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_COLLECT_FORM_TMPLT
    {
        public OBS_COLLECT_FORM_TMPLT()
        {
            this.OBS_API_EVENT_LOG = new HashSet<OBS_API_EVENT_LOG>();
            this.OBS_COL_FORM_QUESTIONS = new HashSet<OBS_COL_FORM_QUESTIONS>();
            this.OBS_COL_FORM_TMPLT_ATTRIBS = new HashSet<OBS_COL_FORM_TMPLT_ATTRIBS>();
            this.OBS_COLLECT_FORM_INST = new HashSet<OBS_COLLECT_FORM_INST>();
        }
    
        public int obs_cft_id { get; set; }
        public int obs_type_id { get; set; }
        public int dsc_cust_id { get; set; }
        public int dsc_lc_id { get; set; }
        public string obs_cft_title { get; set; }
        public string obs_cft_subtitle { get; set; }
        public short obs_cft_nbr { get; set; }
        public short obs_cft_ver { get; set; }
        public Nullable<System.DateTime> obs_cft_last_saved_dtm { get; set; }
        public string obs_cft_pub_by_uid { get; set; }
        public Nullable<System.DateTime> obs_cft_pub_dtm { get; set; }
        public Nullable<System.DateTime> obs_cft_eff_st_dt { get; set; }
        public System.DateTime obs_cft_eff_end_dt { get; set; }
        public string obs_cft_added_uid { get; set; }
        public System.DateTime obs_cft_added_dtm { get; set; }
        public string obs_cft_upd_uid { get; set; }
        public Nullable<System.DateTime> obs_cft_upd_dtm { get; set; }
    
        public virtual DSC_CUSTOMER DSC_CUSTOMER { get; set; }
        public virtual DSC_LC DSC_LC { get; set; }
        public virtual ICollection<OBS_API_EVENT_LOG> OBS_API_EVENT_LOG { get; set; }
        public virtual ICollection<OBS_COL_FORM_QUESTIONS> OBS_COL_FORM_QUESTIONS { get; set; }
        public virtual ICollection<OBS_COL_FORM_TMPLT_ATTRIBS> OBS_COL_FORM_TMPLT_ATTRIBS { get; set; }
        public virtual ICollection<OBS_COLLECT_FORM_INST> OBS_COLLECT_FORM_INST { get; set; }
        public virtual OBS_TYPE OBS_TYPE { get; set; }
    }
}
