//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_API_EVENT_LOG
    {
        public OBS_API_EVENT_LOG()
        {
            this.OBS_API_JSON = new HashSet<OBS_API_JSON>();
        }
    
        public long obs_api_event_log_id { get; set; }
        public short obs_API_RA_ID { get; set; }
        public short obs_app_id { get; set; }
        public Nullable<long> obs_inst_id { get; set; }
        public Nullable<long> obs_cfi_id { get; set; }
        public Nullable<int> obs_cft_id { get; set; }
        public Nullable<int> dsc_emp_id { get; set; }
        public System.DateTime api_call_rcvd_dtm { get; set; }
        public Nullable<System.DateTime> api_call_sent_dtm { get; set; }
        public string api_call_status { get; set; }
        public string obs_inst_event_text { get; set; }
    
        public virtual DSC_EMPLOYEE DSC_EMPLOYEE { get; set; }
        public virtual ICollection<OBS_API_JSON> OBS_API_JSON { get; set; }
        public virtual OBS_APPLICATION OBS_APPLICATION { get; set; }
        public virtual OBS_COLLECT_FORM_INST OBS_COLLECT_FORM_INST { get; set; }
        public virtual OBS_COLLECT_FORM_TMPLT OBS_COLLECT_FORM_TMPLT { get; set; }
        public virtual OBS_INST OBS_INST { get; set; }
        public virtual OBS_API_RSRC_ACTION OBS_API_RSRC_ACTION { get; set; }
    }
}
