//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_USER_AUTH
    {
        public OBS_USER_AUTH()
        {
            this.OBS_USER_ROLE = new HashSet<OBS_USER_ROLE>();
        }
    
        public int obs_user_auth_id { get; set; }
        public string obs_user_auth_dsc_ad_name { get; set; }
        public string obs_user_auth_active_yn { get; set; }
    
        public virtual ICollection<OBS_USER_ROLE> OBS_USER_ROLE { get; set; }
    }
}
