//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_TYPE_SUB_TYPES
    {
        public int otst_id { get; set; }
        public int obs_type_id { get; set; }
        public int obs_sub_type_id { get; set; }
        public Nullable<System.DateTime> obs_sub_type_end_eff_dt { get; set; }
    
        public virtual OBS_SUB_TYPE OBS_SUB_TYPE { get; set; }
        public virtual OBS_TYPE OBS_TYPE { get; set; }
    }
}
