//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_FORM_ATTRIBS
    {
        public OBS_FORM_ATTRIBS()
        {
            this.OBS_COL_FORM_INST_ATTRIB_VALS = new HashSet<OBS_COL_FORM_INST_ATTRIB_VALS>();
            this.OBS_COL_FORM_TMPLT_ATTRIBS = new HashSet<OBS_COL_FORM_TMPLT_ATTRIBS>();
        }
    
        public int obs_form_attrib_id { get; set; }
        public short obs_attrib_data_type_id { get; set; }
        public string obs_form_attrib_name { get; set; }
        public string obs_form_attrib_desc { get; set; }
        public string obs_form_attrib_display_txt { get; set; }
        public Nullable<short> obs_form_attrib_max_len { get; set; }
        public string obs_form_attrib_min_val { get; set; }
        public string obs_form_attrib_max_val { get; set; }
    
        public virtual OBS_ATTRIB_DATA_TYPES OBS_ATTRIB_DATA_TYPES { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_ATTRIB_VALS> OBS_COL_FORM_INST_ATTRIB_VALS { get; set; }
        public virtual ICollection<OBS_COL_FORM_TMPLT_ATTRIBS> OBS_COL_FORM_TMPLT_ATTRIBS { get; set; }
    }
}
