//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_SUPER_TYPE
    {
        public OBS_SUPER_TYPE()
        {
            this.OBS_TYPE = new HashSet<OBS_TYPE>();
        }
    
        public short obs_super_type_id { get; set; }
        public string obs_super_type_name { get; set; }
        public string obs_super_type_desc { get; set; }
        public string obs_super_type_col_form_only_yn { get; set; }
        public string obs_super_type_api_tag_val { get; set; }
    
        public virtual ICollection<OBS_TYPE> OBS_TYPE { get; set; }
    }
}
