//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_COL_FORM_TMPLT_ATTRIBS
    {
        public long obs_cfta_id { get; set; }
        public int obs_cft_id { get; set; }
        public int obs_form_attrib_id { get; set; }
        public string obs_cfta_hdr_ftr_ind { get; set; }
        public short obs_cfta_disp_order { get; set; }
        public System.DateTime obs_cfta_eff_st_dt { get; set; }
        public System.DateTime obs_cfta_eff_end_dt { get; set; }
    
        public virtual OBS_COLLECT_FORM_TMPLT OBS_COLLECT_FORM_TMPLT { get; set; }
        public virtual OBS_FORM_ATTRIBS OBS_FORM_ATTRIBS { get; set; }
    }
}
