//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_QUEST_ANS_TYPES
    {
        public OBS_QUEST_ANS_TYPES()
        {
            this.OBS_COL_FORM_QUESTIONS = new HashSet<OBS_COL_FORM_QUESTIONS>();
            this.OBS_QUEST_SLCT_ANS = new HashSet<OBS_QUEST_SLCT_ANS>();
        }
    
        public int obs_qat_id { get; set; }
        public int obs_question_id { get; set; }
        public short obs_ans_type_id { get; set; }
        public Nullable<System.DateTime> obs_qat_end_eff_dt { get; set; }
        public string obs_qat_default_ans_type_yn { get; set; }
    
        public virtual OBS_ANS_TYPE OBS_ANS_TYPE { get; set; }
        public virtual ICollection<OBS_COL_FORM_QUESTIONS> OBS_COL_FORM_QUESTIONS { get; set; }
        public virtual OBS_QUESTION OBS_QUESTION { get; set; }
        public virtual ICollection<OBS_QUEST_SLCT_ANS> OBS_QUEST_SLCT_ANS { get; set; }
    }
}
