//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_COLLECT_FORM_INST
    {
        public OBS_COLLECT_FORM_INST()
        {
            this.OBS_API_EVENT_LOG = new HashSet<OBS_API_EVENT_LOG>();
            this.OBS_COL_FORM_INST_ATTRIB_VALS = new HashSet<OBS_COL_FORM_INST_ATTRIB_VALS>();
            this.OBS_COL_FORM_INST_MM_ATTACH = new HashSet<OBS_COL_FORM_INST_MM_ATTACH>();
            this.OBS_COL_FORM_INST_QUEST = new HashSet<OBS_COL_FORM_INST_QUEST>();
            this.OBS_COL_FORM_INST_SIGS = new HashSet<OBS_COL_FORM_INST_SIGS>();
        }
    
        public long obs_cfi_id { get; set; }
        public long obs_inst_id { get; set; }
        public int obs_cft_id { get; set; }
        public int dsc_observer_emp_id { get; set; }
        public System.DateTime obs_cfi_start_dt { get; set; }
        public Nullable<System.DateTime> obs_cfi_last_upd_dt { get; set; }
        public Nullable<System.DateTime> obs_cfi_comp_date { get; set; }
    
        public virtual DSC_EMPLOYEE DSC_EMPLOYEE { get; set; }
        public virtual ICollection<OBS_API_EVENT_LOG> OBS_API_EVENT_LOG { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_ATTRIB_VALS> OBS_COL_FORM_INST_ATTRIB_VALS { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_MM_ATTACH> OBS_COL_FORM_INST_MM_ATTACH { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_QUEST> OBS_COL_FORM_INST_QUEST { get; set; }
        public virtual ICollection<OBS_COL_FORM_INST_SIGS> OBS_COL_FORM_INST_SIGS { get; set; }
        public virtual OBS_COLLECT_FORM_TMPLT OBS_COLLECT_FORM_TMPLT { get; set; }
        public virtual OBS_INST OBS_INST { get; set; }
    }
}
