//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBS_COL_FORM_INST_ATTRIB_VALS
    {
        public long obs_cfiav_id { get; set; }
        public int obs_form_attrib_id { get; set; }
        public long obs_cfi_id { get; set; }
        public string obs_cfiav_value { get; set; }
    
        public virtual OBS_FORM_ATTRIBS OBS_FORM_ATTRIBS { get; set; }
        public virtual OBS_COLLECT_FORM_INST OBS_COLLECT_FORM_INST { get; set; }
    }
}
